# Generated by Django 4.1.2 on 2022-10-31 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='total_fat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='total_calories',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='total_carbs',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='total_protein',
            field=models.FloatField(null=True),
        ),
    ]
