# Generated by Django 4.1.2 on 2022-10-31 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_meal_total_fat_alter_meal_total_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='meal',
            name='food',
            field=models.ManyToManyField(blank=True, to='meals.food'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
