# Generated by Django 4.1.2 on 2022-11-01 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meals', '0005_trainerprofile_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50, null=True)),
                ('company', models.CharField(max_length=100)),
                ('role', models.CharField(default='client', max_length=10)),
                ('username', models.CharField(max_length=100)),
                ('country', models.CharField(default='USA', max_length=4)),
                ('contact', models.CharField(default='(555) 555-5555', max_length=16)),
                ('email', models.EmailField(max_length=100)),
                ('currentPlan', models.CharField(default='enterprise', max_length=100)),
                ('status', models.CharField(default='active', max_length=24)),
                ('avatar', models.CharField(default='https://personal-portfolio-v2-ae3h.vercel.app/images/formal-image-joe-s.png', max_length=100)),
                ('avatarColor', models.CharField(default='primary', max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
