# Generated by Django 4.1.2 on 2022-11-01 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_clientprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField(auto_now_add=True)),
                ('checkin_mood', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=1)),
                ('back_photo', models.CharField(default='https://personal-portfolio-v2-ae3h.vercel.app/images/formal-image-joe-s.png', max_length=100, null=True)),
                ('front_photo', models.CharField(default='https://personal-portfolio-v2-ae3h.vercel.app/images/formal-image-joe-s.png', max_length=100, null=True)),
                ('side_photo', models.CharField(default='https://personal-portfolio-v2-ae3h.vercel.app/images/formal-image-joe-s.png', max_length=100, null=True)),
                ('weight', models.FloatField()),
                ('body_fat_mass', models.FloatField(null=True)),
                ('body_fat_percentage', models.FloatField(null=True)),
                ('skeletul_muscle_mass', models.FloatField(null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.clientprofile')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.trainerprofile')),
            ],
        ),
    ]
