# Generated by Django 4.1.2 on 2022-11-01 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_clientcheckin'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='trainer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='meals.trainerprofile'),
        ),
    ]
