# Generated by Django 4.1.2 on 2022-11-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0008_clientprofile_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='current_body_fat_mass',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='current_body_fat_percentage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='current_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='current_skeletul_muscle_mass',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='current_weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='starting_body_fat_mass',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='starting_body_fat_percentage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='starting_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='starting_skeletul_muscle_mass',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='starting_weight',
            field=models.IntegerField(null=True),
        ),
    ]
