# Generated by Django 4.1.2 on 2022-11-02 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0011_alter_clientprofile_current_body_fat_mass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcheckin',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
