# Generated by Django 4.1.2 on 2022-11-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0013_remove_meal_food_remove_meal_user_food_meal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='fats',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
