# Generated by Django 4.1.2 on 2022-11-03 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0014_food_fats_alter_food_calories_alter_food_carbs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalContitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meals.clientprofile')),
            ],
        ),
    ]
