# Generated by Django 4.1.2 on 2022-11-03 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0015_medicalcontitions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedicalContitions',
            new_name='ClientMedicalContitions',
        ),
    ]
