# Generated by Django 4.1.2 on 2022-11-03 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0016_rename_medicalcontitions_clientmedicalcontitions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmedicalcontitions',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.clientprofile'),
        ),
    ]
