# Generated by Django 4.1.2 on 2022-11-04 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0018_rename_clientmedicalcontitions_clientmedicalcondition'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientMedicalCondition',
            new_name='Condition',
        ),
    ]
