# Generated by Django 4.1.2 on 2022-11-04 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0019_rename_clientmedicalcondition_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='name',
            new_name='title',
        ),
    ]
