# Generated by Django 4.1.2 on 2022-11-08 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0020_rename_name_meal_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/foods/')),
                ('serving', models.CharField(max_length=255)),
                ('calories', models.FloatField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('carbs', models.FloatField(default=0)),
                ('fats', models.FloatField(default=0)),
                ('saturated_fats', models.FloatField(default=0)),
                ('trans_fats', models.FloatField(default=0)),
                ('polyunsaturated_fats', models.FloatField(default=0)),
                ('monounsaturated_fats', models.FloatField(default=0)),
                ('cholesterol', models.FloatField(default=0)),
                ('sodium', models.FloatField(default=0)),
                ('potassium', models.FloatField(default=0)),
                ('fiber', models.FloatField(default=0)),
                ('sugar', models.FloatField(default=0)),
                ('vitamin_a', models.FloatField(default=0)),
                ('vitamin_c', models.FloatField(default=0)),
                ('calcium', models.FloatField(default=0)),
                ('iron', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='food',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meals.meal'),
        ),
    ]
